print("===Resume===")
print("Name : Alice Johnson")
print("Email : alice@gmail.com")
print("Skills :")
print("-Java")
print("-HTML & CSS")
print("-Problem Solving")
print("Experience : 2 years at XYZ Ltd.")